name: nyoba_modul_5
description: "ini merupakan project development kelompok 4"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.8.0
  flutter_spinkit: ^5.2.0
  salomon_bottom_bar: ^3.3.2
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4 # atau versi terkini
  flutter_facebook_auth: ^6.0.2
  firebase_storage: ^11.2.0
  image_picker: ^1.0.4
  lottie: ^3.3.1
  http: ^1.4.0
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/icon/sepeda.gif
    - assets/image/tambal_ban.jpg
    - assets/icon/sepeda.json
    - assets/icon/motor.png
    - assets/icon/truck.png
    - assets/icon/mobil.png
    - assets/icon/bicycle.png
    - assets/icon/lokasi.json
    - assets/icon/loading.json
    - assets/fonts/Hello-Botuna.ttf

fonts:
  - family: Poppins
  - family: HelloBotuna
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Hello-Botuna.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
